In [2]:
import gym
import gym_maze
import numpy as np
import random

In [3]:
# Create an environment
env = gym.make("maze-random-10x10-plus-v0")
observation = env.reset()

In [4]:
n_observations = 100
n_actions = env.action_space.n

In [5]:
#Initialize the q-table to 0
q_table = np.zeros((n_observations,n_actions))

In [6]:
# Define the maximum number of iterations
NUM_EPISODES = 1000

In [17]:
# Hyperparameters
alpha = 0.1
gamma = 0.9
epsilon = 0.9

In [18]:
sum = 0
for episode in range(NUM_EPISODES):
    
    #we initialize the first state of the episode
    state = env.reset()
    row = int(state[0])
    col = int(state[1])
    state_num = (row * 10) + col
    done = False
    
    while not done:
        # env.render()
        sum += 1
        epsilon -= 0.001
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state_num]) # Exploit learned values

        next_state, reward, done, truncated = env.step(action) 
        
        next_state_row = next_state[0]
        next_state_col = next_state[1]
        next_state_num = (next_state_row * 10) + next_state_col
        
        old_value = q_table[state_num, action]
        next_max = np.max(q_table[next_state_num])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state_num, action] = new_value

        state_num = next_state_num

    if done or truncated:
        observation = env.reset()
avg = sum // NUM_EPISODES
print(round(avg))

45


In [10]:
print(q_table)

[[0.00521599 0.00665341 0.00473432 0.00611325]
 [0.00599487 0.00974186 0.00568266 0.00835136]
 [0.00938185 0.01384517 0.01125038 0.01212843]
 [0.01491944 0.01870396 0.01712316 0.01749805]
 [0.01737734 0.02698595 0.01885111 0.02266997]
 [0.02383505 0.03753278 0.02906795 0.0295162 ]
 [0.04236467 0.06312099 0.07534869 0.05066818]
 [0.04672428 0.05396041 0.04765858 0.04650914]
 [0.04386979 0.04136706 0.04182316 0.04071112]
 [0.05335081 0.04410391 0.04500033 0.04606412]
 [0.00429376 0.00488505 0.00412996 0.00489809]
 [0.00542504 0.00606341 0.0056241  0.00649878]
 [0.01006231 0.01138437 0.01020643 0.01130931]
 [0.01021949 0.01246013 0.01165994 0.01172743]
 [0.01453097 0.01729083 0.01667506 0.01726917]
 [0.06446139 0.06572181 0.06748287 0.06345554]
 [0.0572466  0.06065673 0.09860273 0.04828605]
 [0.07068411 0.05773276 0.06249952 0.06203372]
 [0.05722786 0.04840874 0.05251083 0.05337968]
 [0.04849564 0.04329099 0.04411078 0.04524744]
 [0.00995324 0.00776386 0.01285782 0.00876904]
 [0.00759299 

In [36]:
# Close the environment
env.close()