In [1]:
import gym
import gym_maze
import numpy as np
import random

In [2]:
# Create an environment
env = gym.make("maze-random-10x10-plus-v0")
observation = env.reset()

In [3]:
n_observations = 100
n_actions = env.action_space.n

In [4]:
#Initialize the q-table to 0
q_table = np.zeros((n_observations,n_actions))

In [5]:
# Define the maximum number of iterations
NUM_EPISODES = 1000

In [6]:
# Hyperparameters
alpha = 0.9
gamma = 0.9
epsilon = 0.9

In [ ]:
counter = 0

In [9]:
for episode in range(NUM_EPISODES):
    #we initialize the first state of the episode
    state = env.reset()
    row = int(state[0])
    col = int(state[1])
    state_num = (row * 10) + col
    done = False
        
    while not done:
        env.render()
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state_num]) # Exploit learned values

        next_state, reward, done, truncated = env.step(action) 
        
        next_state_row = next_state[0]
        next_state_col = next_state[1]
        next_state_num = (next_state_row * 10) + next_state_col
        
        old_value = q_table[state_num, action]
        next_max = np.max(q_table[next_state_num])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state_num, action] = new_value

        if done:
            counter += 1

        state_num = next_state_num

    # TODO: Implement the agent policy here
    # Note: .sample() is used to sample random action from the environment's action space

    # Choose an action (Replace this random action with your agent's policy)
    # action = env.action_space.sample()

    # Perform the action and receive feedback from the environment
    # next_state, reward, done, truncated = env.step(action)

    if done or truncated:
        observation = env.reset()

KeyboardInterrupt: 

In [8]:
print(counter)
print(q_table)

[[0.23993827 0.2540719  0.24690972 0.23532514]
 [0.18638973 0.3259726  0.23505996 0.2302788 ]
 [0.19007338 0.31100791 0.32569409 0.39398848]
 [0.33702708 0.42804639 0.3410478  0.38884048]
 [0.32374768 0.47569149 0.46933996 0.43307818]
 [0.34378541 0.33552768 0.33975736 0.355678  ]
 [0.27337684 0.28587205 0.30161185 0.28630411]
 [0.30286977 0.28152202 0.34253834 0.29722419]
 [0.33457021 0.37504282 0.34833963 0.34607193]
 [0.39570385 0.29802709 0.30804088 0.3119988 ]
 [0.21742387 0.1899809  0.25408529 0.19587765]
 [0.20400163 0.20810274 0.20943576 0.2059015 ]
 [0.19420279 0.32307934 0.19424181 0.19376469]
 [0.24611721 0.38209692 0.29416564 0.38214914]
 [0.34222046 0.32822258 0.2688299  0.32928255]
 [0.2642968  0.44177814 0.38696033 0.41272797]
 [0.33597546 0.34298983 0.3248051  0.2806688 ]
 [0.29944356 0.2841139  0.28949654 0.28338495]
 [0.34372804 0.33994296 0.32631706 0.39262649]
 [0.30193082 0.30571193 0.2939379  0.28557377]
 [0.24460182 0.21607486 0.26677621 0.2170515 ]
 [0.22188111 

In [16]:
# Close the environment
env.close()